///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Regression_BitbucketTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Regression_BitbucketTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("66939c33-cd17-4633-abfa-22457226b0d8")]
    public partial class Regression_BitbucketTestRepository : RepoGenBaseFolder
    {
        static Regression_BitbucketTestRepository instance = new Regression_BitbucketTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Regression_BitbucketTestRepository element repository.
        /// </summary>
        [RepositoryFolder("66939c33-cd17-4633-abfa-22457226b0d8")]
        public static Regression_BitbucketTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Regression_BitbucketTestRepository() 
            : base("Regression_BitbucketTestRepository", "/", null, 0, false, "66939c33-cd17-4633-abfa-22457226b0d8", ".\\RepositoryImages\\Regression_BitbucketTestRepository66939c33.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("66939c33-cd17-4633-abfa-22457226b0d8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class Regression_BitbucketTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}