///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the testRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("aeb90129-d5c5-48ba-8ea1-775c5d210fc6")]
    public partial class testRepository : RepoGenBaseFolder
    {
        static testRepository instance = new testRepository();

        /// <summary>
        /// Gets the singleton class instance representing the testRepository element repository.
        /// </summary>
        [RepositoryFolder("aeb90129-d5c5-48ba-8ea1-775c5d210fc6")]
        public static testRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public testRepository() 
            : base("testRepository", "/", null, 0, false, "aeb90129-d5c5-48ba-8ea1-775c5d210fc6", ".\\RepositoryImages\\testRepositoryaeb90129.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("aeb90129-d5c5-48ba-8ea1-775c5d210fc6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class testRepositoryFolders
    {
    }
#pragma warning restore 0436
}