///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace test3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the test3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("da2b1276-baf6-4817-b3bf-97a6b23c2603")]
    public partial class test3Repository : RepoGenBaseFolder
    {
        static test3Repository instance = new test3Repository();

        /// <summary>
        /// Gets the singleton class instance representing the test3Repository element repository.
        /// </summary>
        [RepositoryFolder("da2b1276-baf6-4817-b3bf-97a6b23c2603")]
        public static test3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public test3Repository() 
            : base("test3Repository", "/", null, 0, false, "da2b1276-baf6-4817-b3bf-97a6b23c2603", ".\\RepositoryImages\\test3Repositoryda2b1276.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("da2b1276-baf6-4817-b3bf-97a6b23c2603")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class test3RepositoryFolders
    {
    }
#pragma warning restore 0436
}