///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace test_r1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the test_r1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("2ecd9d08-6432-41e3-ba6a-a5518cbeb370")]
    public partial class test_r1Repository : RepoGenBaseFolder
    {
        static test_r1Repository instance = new test_r1Repository();
        test_r1RepositoryFolders.TrunkAppFolder _trunk;

        /// <summary>
        /// Gets the singleton class instance representing the test_r1Repository element repository.
        /// </summary>
        [RepositoryFolder("2ecd9d08-6432-41e3-ba6a-a5518cbeb370")]
        public static test_r1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public test_r1Repository() 
            : base("test_r1Repository", "/", null, 0, false, "2ecd9d08-6432-41e3-ba6a-a5518cbeb370", ".\\RepositoryImages\\test_r1Repository2ecd9d08.rximgres")
        {
            _trunk = new test_r1RepositoryFolders.TrunkAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2ecd9d08-6432-41e3-ba6a-a5518cbeb370")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Trunk folder.
        /// </summary>
        [RepositoryFolder("db4a4d3e-c965-4334-a7c8-4c5ae9d067ff")]
        public virtual test_r1RepositoryFolders.TrunkAppFolder Trunk
        {
            get { return _trunk; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class test_r1RepositoryFolders
    {
        /// <summary>
        /// The TrunkAppFolder folder.
        /// </summary>
        [RepositoryFolder("db4a4d3e-c965-4334-a7c8-4c5ae9d067ff")]
        public partial class TrunkAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemsviewInfo;

            /// <summary>
            /// Creates a new Trunk  folder.
            /// </summary>
            public TrunkAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Trunk", "/form[@title='trunk']", parentFolder, 30000, null, true, "db4a4d3e-c965-4334-a7c8-4c5ae9d067ff", "")
            {
                _itemsviewInfo = new RepoItemInfo(this, "ItemsView", "element[@class='ShellTabWindowClass']//element[@instance='1']/container[@caption='ShellView']/?/?/list[@accessiblename='Items View']", 30000, null, "573c4379-acaa-43bc-9ce7-9a31980ff2c2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("db4a4d3e-c965-4334-a7c8-4c5ae9d067ff")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("db4a4d3e-c965-4334-a7c8-4c5ae9d067ff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ItemsView item.
            /// </summary>
            [RepositoryItem("573c4379-acaa-43bc-9ce7-9a31980ff2c2")]
            public virtual Ranorex.List ItemsView
            {
                get
                {
                    return _itemsviewInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ItemsView item info.
            /// </summary>
            [RepositoryItemInfo("573c4379-acaa-43bc-9ce7-9a31980ff2c2")]
            public virtual RepoItemInfo ItemsViewInfo
            {
                get
                {
                    return _itemsviewInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}